Repository MOV-AI/movai-core-shared, pull requests merged in 2023-08, with the labels that each got.

#93 BP-1071 - upgrade stress handler to have insert and query tests as well
  movai_core_shared/consts.py
  movai_core_shared/messages/stress_data.py
Labels: enhancement

#95 BP-1074 - update TimeSeriesDBHandler to support bulk inserts
  movai_core_shared/consts.py
  movai_core_shared/core/message_client.py
  movai_core_shared/core/zmq_server.py
  movai_core_shared/envvars.py
Labels: enhancement

#98 BP-1079 - backend does not start
  movai_core_shared/core/message_client.py
  movai_core_shared/core/zmq_client.py
Labels: bug

#97 Version 2.4.1.24
  movai_core_shared/consts.py
  movai_core_shared/core/message_client.py
  movai_core_shared/core/zmq_client.py
  movai_core_shared/core/zmq_server.py
  movai_core_shared/envvars.py
  movai_core_shared/messages/stress_data.py
Labels: bug, enhancement

#99 Bugfix/bp 1079/backend does not start
  movai_core_shared/core/zmq_client.py
Labels: bug

#101 BP-1081 - remove async message client
  movai_core_shared/core/base_command.py
  movai_core_shared/core/message_client.py
  movai_core_shared/core/secure.py
  movai_core_shared/core/securepassword.py
  movai_core_shared/core/zmq_base.py
  movai_core_shared/core/zmq_client.py
  movai_core_shared/core/zmq_server.py
  movai_core_shared/envvars.py
  movai_core_shared/logger.py
Labels: bug

#105 BP-1084: removed lock since we don't have threads anymore
  movai_core_shared/core/zmq_client.py
  movai_core_shared/core/zmq_server.py
  movai_core_shared/envvars.py
Labels: enhancement
